---
version: "3.6"

services:
  search_service_test:
    build:
      context: .
      dockerfile: test.DockerFile
    depends_on:
      localstack:
        condition: service_healthy
    working_dir: /go/src/app
    env_file:
      - docker-compose.env
    volumes:
      - .:/go/src/app

  search_service_gosec:
    image: securego/gosec:2.15.0
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app
    entrypoint: ["/bin/gosec", "/go/src/app/..."]

  postgres:
    ports: ["5434:5432"]
