---
version: "3.6"

services:
  search_service_test:
    build:
      context: .
      dockerfile: test.DockerFile
    depends_on:
      localstack:
        condition: service_healthy
    working_dir: /go/src/app
    env_file:
      - docker-compose.env
    volumes:
      - .:/go/src/app

  search_service_gosec:
    image: securego/gosec:2.17.0@sha256:4ea9b6053eac43abda841af5885bbd31ee1bf7289675545b8858bcedb40b4fa8
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app
    entrypoint: ["/bin/gosec", "/go/src/app/..."]

  postgres:
    ports: ["5434:5432"]
