---
version: "3.7"

services:
  search_service:
    image: 311462405659.dkr.ecr.eu-west-1.amazonaws.com/search_service:latest
    build: .
    ports:
      - 8000:8000
    depends_on:
      localstack:
        condition: service_healthy
    env_file:
      - docker-compose.env

  localstack:
    image: localstack/localstack:2.2.0
    environment:
      AWS_DEFAULT_REGION: eu-west-1
      SERVICES: es, secretsmanager
    networks:
      default:
        aliases:
          - search-service.eu-west-1.es.localhost.localstack.cloud
    volumes:
      - "./scripts/localstack/init:/etc/localstack/init/ready.d"
      - "./scripts/localstack/wait:/scripts/wait"
    healthcheck:
      test: bash /scripts/wait/healthcheck.sh
      interval: 30s
      timeout: 5s
      retries: 8

  postgres:
    image: postgres:15.3
    command: postgres
    environment:
      POSTGRES_USER: searchservice
      POSTGRES_PASSWORD: searchservice
      POSTGRES_DB: searchservice
      PGPASSWORD: searchservice

  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: /tmp/openapi.yml
    volumes:
      - ./docs/openapi/openapi.yml:/tmp/openapi.yml
    ports:
      - 8383:8080

  swagger-generate:
    image: quay.io/goswagger/swagger
    environment:
      GO111MODULE: "off"
      GOPATH: /go
    volumes:
      - ./:/go/src
    working_dir: /go/src
    entrypoint: ["swagger", "generate", "spec", "-o", "/go/src/docs/openapi/openapi.yml", "--scan-models"]

  wait-for-it:
    image: wait-for-it
    build: ./wait-for-it
